version: '3.9'

services:
  app:
    image: beer-front-app
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: taptreck
    ports:
      - "8097:8097"
    environment:
      - "SERVER_PORT=8097"
    restart: always